version: '3.8'
services:
  python_etl_executor:
    build:
      context: .
      dockerfile: Dockerfile.python_etl_executor
    image: datawarehouse-python_etl_executor:latest
    volumes:
      - ./:/app
      - ./result:/app/result
    working_dir: /app
    command: ["python", "main.py"]
    restart: "no"

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: datawarehouse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./load_data.sql:/docker-entrypoint-initdb.d/load_data.sql
      - ./result:/data
    depends_on:
      - python_etl_executor
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - |
        until [ -f /data/organization_data_breaches_unified.csv ] && \
              [ -f /data/Global_Cybersecurity_Threats_unified.csv ] && \
              [ -f /data/LossFromNetCrime_unified.csv ]; 
        do 
          echo 'Waiting for result files...'; 
          sleep 2; 
        done; 
        exec docker-entrypoint.sh postgres

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
  pgadmin_data:
